apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cms-web
  template:
    metadata:
      labels:
        app: cms-web
    spec:
      containers:
        - name: cms-web
          image: somkumarva/cms-web:3
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: web-env-file
              readOnly: true
              mountPath: /usr/src/app/apps/web/.env
              subPath: .env
            - name: db-env-file
              readOnly: true
              mountPath: /usr/src/app/packages/db/.env
              subPath: .env
      volumes:
        - name: web-env-file
          secret:
            secretName: cms-web-secret
        - name: db-env-file
          secret:
            secretName: cms-db-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cms-worker
  template:
    metadata:
      labels:
        app: cms-worker
    spec:
      containers:
        - name: cms-worker
          image: somkumarva/cms-worker:3
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: worker-env-file
              readOnly: true
              mountPath: /usr/src/app/apps/worker/.env
              subPath: .env
      volumes:
        - name: worker-env-file
          secret:
            secretName: cms-worker-secret