apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-web
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: cms-web
  template:
    metadata:
      labels:
        app: cms-web
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
        - name: cms-web
          image: somkumarva/cms-web:5f269f3d0dd0e9eba813684afe7a5a0e2e659260
          ports:
            - containerPort: 3000
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: web-env-file
              readOnly: true
              mountPath: /usr/src/app/apps/web/.env
              subPath: .env
            - name: db-env-file
              readOnly: true
              mountPath: /usr/src/app/packages/db/.env
              subPath: .env
      volumes:
        - name: web-env-file
          secret:
            secretName: cms-web-secret
        - name: db-env-file
          secret:
            secretName: cms-db-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-worker
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: cms-worker
  template:
    metadata:
      labels:
        app: cms-worker
    spec:
      containers:
        - name: cms-worker
          image: somkumarva/cms-worker:c4267a954aaf39cf0746539ece686316a33af478
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: worker-env-file
              readOnly: true
              mountPath: /usr/src/app/apps/worker/.env
              subPath: .env
      volumes:
        - name: worker-env-file
          secret:
            secretName: cms-worker-secret
