apiVersion: v1
kind: Service
metadata:
  name: cms-web-service
spec:
  selector:
    app: cms-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: cms-worker-service
spec:
  selector:
    app: cms-worker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP