global:
  postgresql:
    auth:
      username: postgres
      password: pass
      database: cms
primary:
  persistence:
    enabled: true
    existingClaim: pg-data
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    runAsUser: 1001

service:
  type: ClusterIp
  port: 5432
