architecture: standalone

auth:
  enabled: true
  password: "pass" # put a real password here

primary:
  persistence:
    enabled: true
    existingClaim: redis-data # <-- this is the PVC we created
  podSecurityContext:
    fsGroup: 1001
  containerSecurityContext:
    runAsUser: 1001

volumePermissions:
  enabled: true
